<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.

/**
 * Privacy provider for the AI Quiz Generator plugin.
 *
 * Implements GDPR compliance.
 *
 * @package    local_hlai_quizgen
 * @copyright  2025 Human Logic Software LLC
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

namespace local_hlai_quizgen\privacy;

use core_privacy\local\metadata\collection;
use core_privacy\local\metadata\provider as metadata_provider;
use core_privacy\local\request\approved_contextlist;
use core_privacy\local\request\approved_userlist;
use core_privacy\local\request\contextlist;
use core_privacy\local\request\core_userlist_provider;
use core_privacy\local\request\plugin\provider as plugin_provider;
use core_privacy\local\request\transform;
use core_privacy\local\request\userlist;
use core_privacy\local\request\writer;


/**
 * Privacy provider class.
 */
class provider implements
    core_userlist_provider,
    metadata_provider,
    plugin_provider {
    /**
     * Get metadata about data stored by this plugin.
     *
     * @param collection $collection Collection to add items to
     * @return collection Updated collection
     */
    public static function get_metadata(collection $collection): collection {
        // Request data.
        $collection->add_database_table(
            'local_hlai_quizgen_requests',
            [
                'userid' => 'privacy:metadata:local_hlai_quizgen_requests:userid',
                'courseid' => 'privacy:metadata:local_hlai_quizgen_requests:courseid',
                'status' => 'privacy:metadata:local_hlai_quizgen_requests:status',
                'content_sources' => 'privacy:metadata:local_hlai_quizgen_requests:content_sources',
                'total_questions' => 'privacy:metadata:local_hlai_quizgen_requests:total_questions',
                'processing_mode' => 'privacy:metadata:local_hlai_quizgen_requests:processing_mode',
                'custom_instructions' => 'privacy:metadata:local_hlai_quizgen_requests:custom_instructions',
                'category_name' => 'privacy:metadata:local_hlai_quizgen_requests:category_name',
                'timecreated' => 'privacy:metadata:local_hlai_quizgen_requests:timecreated',
            ],
            'privacy:metadata:local_hlai_quizgen_requests'
        );

        // User settings.
        $collection->add_database_table(
            'local_hlai_quizgen_settings',
            [
                'userid' => 'privacy:metadata:local_hlai_quizgen_settings:userid',
                'courseid' => 'privacy:metadata:local_hlai_quizgen_settings:courseid',
                'setting_name' => 'privacy:metadata:local_hlai_quizgen_settings:setting_name',
                'setting_value' => 'privacy:metadata:local_hlai_quizgen_settings:setting_value',
                'timecreated' => 'privacy:metadata:local_hlai_quizgen_settings:timecreated',
            ],
            'privacy:metadata:local_hlai_quizgen_settings'
        );

        // Logs.
        $collection->add_database_table(
            'local_hlai_quizgen_logs',
            [
                'userid' => 'privacy:metadata:local_hlai_quizgen_logs:userid',
                'action' => 'privacy:metadata:local_hlai_quizgen_logs:action',
                'component' => 'privacy:metadata:local_hlai_quizgen_logs:component',
                'details' => 'privacy:metadata:local_hlai_quizgen_logs:details',
                'status' => 'privacy:metadata:local_hlai_quizgen_logs:status',
                'error_message' => 'privacy:metadata:local_hlai_quizgen_logs:error_message',
                'timecreated' => 'privacy:metadata:local_hlai_quizgen_logs:timecreated',
            ],
            'privacy:metadata:local_hlai_quizgen_logs'
        );

        // Questions generated by users.
        $collection->add_database_table(
            'local_hlai_quizgen_questions',
            [
                'userid' => 'privacy:metadata:local_hlai_quizgen_questions:userid',
                'courseid' => 'privacy:metadata:local_hlai_quizgen_questions:courseid',
                'questiontext' => 'privacy:metadata:local_hlai_quizgen_questions:questiontext',
                'questiontype' => 'privacy:metadata:local_hlai_quizgen_questions:questiontype',
                'difficulty' => 'privacy:metadata:local_hlai_quizgen_questions:difficulty',
                'blooms_level' => 'privacy:metadata:local_hlai_quizgen_questions:blooms_level',
                'generalfeedback' => 'privacy:metadata:local_hlai_quizgen_questions:generalfeedback',
                'ai_reasoning' => 'privacy:metadata:local_hlai_quizgen_questions:ai_reasoning',
                'status' => 'privacy:metadata:local_hlai_quizgen_questions:status',
                'timecreated' => 'privacy:metadata:local_hlai_quizgen_questions:timecreated',
            ],
            'privacy:metadata:local_hlai_quizgen_questions'
        );

        // Wizard session state.
        $collection->add_database_table(
            'local_hlai_quizgen_wizstate',
            [
                'userid' => 'privacy:metadata:local_hlai_quizgen_wizstate:userid',
                'courseid' => 'privacy:metadata:local_hlai_quizgen_wizstate:courseid',
                'current_step' => 'privacy:metadata:local_hlai_quizgen_wizstate:current_step',
                'state_data' => 'privacy:metadata:local_hlai_quizgen_wizstate:state_data',
                'timecreated' => 'privacy:metadata:local_hlai_quizgen_wizstate:timecreated',
            ],
            'privacy:metadata:local_hlai_quizgen_wizstate'
        );

        // Rate limit tracking.
        $collection->add_database_table(
            'local_hlai_quizgen_ratelog',
            [
                'userid' => 'privacy:metadata:local_hlai_quizgen_ratelog:userid',
                'limittype' => 'privacy:metadata:local_hlai_quizgen_ratelog:limittype',
                'details' => 'privacy:metadata:local_hlai_quizgen_ratelog:details',
                'timecreated' => 'privacy:metadata:local_hlai_quizgen_ratelog:timecreated',
            ],
            'privacy:metadata:local_hlai_quizgen_ratelog'
        );

        // User templates.
        $collection->add_database_table(
            'local_hlai_quizgen_templates',
            [
                'userid' => 'privacy:metadata:local_hlai_quizgen_templates:userid',
                'courseid' => 'privacy:metadata:local_hlai_quizgen_templates:courseid',
                'name' => 'privacy:metadata:local_hlai_quizgen_templates:name',
                'description' => 'privacy:metadata:local_hlai_quizgen_templates:description',
                'config_data' => 'privacy:metadata:local_hlai_quizgen_templates:config_data',
                'timecreated' => 'privacy:metadata:local_hlai_quizgen_templates:timecreated',
            ],
            'privacy:metadata:local_hlai_quizgen_templates'
        );

        // Peer review data.
        $collection->add_database_table(
            'local_hlai_quizgen_reviews',
            [
                'reviewerid' => 'privacy:metadata:local_hlai_quizgen_reviews:reviewerid',
                'submitterid' => 'privacy:metadata:local_hlai_quizgen_reviews:submitterid',
                'status' => 'privacy:metadata:local_hlai_quizgen_reviews:status',
                'decision' => 'privacy:metadata:local_hlai_quizgen_reviews:decision',
                'decision_comments' => 'privacy:metadata:local_hlai_quizgen_reviews:decision_comments',
                'instructions' => 'privacy:metadata:local_hlai_quizgen_reviews:instructions',
                'timecreated' => 'privacy:metadata:local_hlai_quizgen_reviews:timecreated',
            ],
            'privacy:metadata:local_hlai_quizgen_reviews'
        );

        // Question revisions.
        $collection->add_database_table(
            'local_hlai_quizgen_revisions',
            [
                'userid' => 'privacy:metadata:local_hlai_quizgen_revisions:userid',
                'changes' => 'privacy:metadata:local_hlai_quizgen_revisions:changes',
                'revision_notes' => 'privacy:metadata:local_hlai_quizgen_revisions:revision_notes',
                'timecreated' => 'privacy:metadata:local_hlai_quizgen_revisions:timecreated',
            ],
            'privacy:metadata:local_hlai_quizgen_revisions'
        );

        // External data sent to AI gateway for quiz generation.
        $collection->add_external_location_link(
            'aigateway',
            [
                'content' => 'privacy:metadata:external:aigateway:content',
                'courseid' => 'privacy:metadata:external:aigateway:courseid',
            ],
            'privacy:metadata:external:aigateway:purpose'
        );

        // External URLs fetched for content extraction (user-provided URLs).
        $collection->add_external_location_link(
            'urlcontent',
            [
                'url' => 'privacy:metadata:external:urlcontent:url',
            ],
            'privacy:metadata:external:urlcontent:purpose'
        );

        return $collection;
    }

    /**
     * Get contexts containing user data.
     *
     * @param int $userid User ID
     * @return contextlist Context list
     */
    public static function get_contexts_for_userid(int $userid): contextlist {
        $contextlist = new contextlist();
        $params = [
            'courselevel' => CONTEXT_COURSE,
            'userid' => $userid,
        ];

        // Courses where user has requests.
        $sql = "SELECT DISTINCT ctx.id
                  FROM {context} ctx
                  JOIN {course} c ON c.id = ctx.instanceid AND ctx.contextlevel = :courselevel
                  JOIN {local_hlai_quizgen_requests} r ON r.courseid = c.id
                 WHERE r.userid = :userid";
        $contextlist->add_from_sql($sql, $params);

        // Courses where user has questions.
        $sql = "SELECT DISTINCT ctx.id
                  FROM {context} ctx
                  JOIN {course} c ON c.id = ctx.instanceid AND ctx.contextlevel = :courselevel
                  JOIN {local_hlai_quizgen_questions} q ON q.courseid = c.id
                 WHERE q.userid = :userid";
        $contextlist->add_from_sql($sql, $params);

        // Courses where user has settings.
        $sql = "SELECT DISTINCT ctx.id
                  FROM {context} ctx
                  JOIN {course} c ON c.id = ctx.instanceid AND ctx.contextlevel = :courselevel
                  JOIN {local_hlai_quizgen_settings} s ON s.courseid = c.id
                 WHERE s.userid = :userid";
        $contextlist->add_from_sql($sql, $params);

        // Courses where user has wizard state.
        $sql = "SELECT DISTINCT ctx.id
                  FROM {context} ctx
                  JOIN {course} c ON c.id = ctx.instanceid AND ctx.contextlevel = :courselevel
                  JOIN {local_hlai_quizgen_wizstate} w ON w.courseid = c.id
                 WHERE w.userid = :userid";
        $contextlist->add_from_sql($sql, $params);

        // Courses where user has templates.
        $sql = "SELECT DISTINCT ctx.id
                  FROM {context} ctx
                  JOIN {course} c ON c.id = ctx.instanceid AND ctx.contextlevel = :courselevel
                  JOIN {local_hlai_quizgen_templates} t ON t.courseid = c.id
                 WHERE t.userid = :userid";
        $contextlist->add_from_sql($sql, $params);

        // Courses where user has reviews (as reviewer or submitter).
        $sql = "SELECT DISTINCT ctx.id
                  FROM {context} ctx
                  JOIN {course} c ON c.id = ctx.instanceid AND ctx.contextlevel = :courselevel
                  JOIN {local_hlai_quizgen_questions} q ON q.courseid = c.id
                  JOIN {local_hlai_quizgen_reviews} rv ON rv.questionid = q.id
                 WHERE rv.reviewerid = :userid OR rv.submitterid = :userid2";
        $contextlist->add_from_sql($sql, array_merge($params, ['userid2' => $userid]));

        return $contextlist;
    }

    /**
     * Get users in a context.
     *
     * @param userlist $userlist User list
     * @return void
     */
    public static function get_users_in_context(userlist $userlist): void {
        $context = $userlist->get_context();

        if ($context->contextlevel != CONTEXT_COURSE) {
            return;
        }

        $params = ['courseid' => $context->instanceid];

        // Users with requests in this course.
        $sql = "SELECT r.userid
                  FROM {local_hlai_quizgen_requests} r
                 WHERE r.courseid = :courseid";
        $userlist->add_from_sql('userid', $sql, $params);

        // Users with questions in this course.
        $sql = "SELECT q.userid
                  FROM {local_hlai_quizgen_questions} q
                 WHERE q.courseid = :courseid";
        $userlist->add_from_sql('userid', $sql, $params);

        // Users with settings in this course.
        $sql = "SELECT s.userid
                  FROM {local_hlai_quizgen_settings} s
                 WHERE s.courseid = :courseid";
        $userlist->add_from_sql('userid', $sql, $params);

        // Users with wizard state in this course.
        $sql = "SELECT w.userid
                  FROM {local_hlai_quizgen_wizstate} w
                 WHERE w.courseid = :courseid";
        $userlist->add_from_sql('userid', $sql, $params);

        // Users with templates in this course.
        $sql = "SELECT t.userid
                  FROM {local_hlai_quizgen_templates} t
                 WHERE t.courseid = :courseid";
        $userlist->add_from_sql('userid', $sql, $params);

        // Users with reviews in this course (as reviewer or submitter).
        $sql = "SELECT rv.reviewerid AS userid
                  FROM {local_hlai_quizgen_reviews} rv
                  JOIN {local_hlai_quizgen_questions} q ON q.id = rv.questionid
                 WHERE q.courseid = :courseid";
        $userlist->add_from_sql('userid', $sql, $params);

        $sql = "SELECT rv.submitterid AS userid
                  FROM {local_hlai_quizgen_reviews} rv
                  JOIN {local_hlai_quizgen_questions} q ON q.id = rv.questionid
                 WHERE q.courseid = :courseid";
        $userlist->add_from_sql('userid', $sql, $params);
    }

    /**
     * Export user data.
     *
     * @param approved_contextlist $contextlist Approved contexts
     * @return void
     */
    public static function export_user_data(approved_contextlist $contextlist): void {
        global $DB;

        $userid = $contextlist->get_user()->id;

        foreach ($contextlist->get_contexts() as $context) {
            if ($context->contextlevel != CONTEXT_COURSE) {
                continue;
            }

            $courseid = $context->instanceid;
            $subcontext = [get_string('pluginname', 'local_hlai_quizgen')];

            // Export requests.
            $rs = $DB->get_recordset('local_hlai_quizgen_requests', [
                'courseid' => $courseid,
                'userid' => $userid,
            ]);
            $data = [];
            foreach ($rs as $request) {
                $data[] = [
                    'status' => $request->status,
                    'total_questions' => $request->total_questions,
                    'questions_generated' => $request->questions_generated,
                    'processing_mode' => $request->processing_mode,
                    'custom_instructions' => $request->custom_instructions ?? '',
                    'category_name' => $request->category_name ?? '',
                    'timecreated' => transform::datetime($request->timecreated),
                    'timecompleted' => $request->timecompleted ? transform::datetime($request->timecompleted) : '-',
                ];
            }
            $rs->close();

            if (!empty($data)) {
                writer::with_context($context)->export_data(
                    array_merge($subcontext, ['requests']),
                    (object)['requests' => $data]
                );
            }

            // Export settings scoped to this course.
            $rs = $DB->get_recordset('local_hlai_quizgen_settings', [
                'userid' => $userid,
                'courseid' => $courseid,
            ]);
            $data = [];
            foreach ($rs as $setting) {
                $data[$setting->setting_name] = $setting->setting_value;
            }
            $rs->close();

            if (!empty($data)) {
                writer::with_context($context)->export_data(
                    array_merge($subcontext, ['settings']),
                    (object)$data
                );
            }

            // Export questions scoped to this course.
            $rs = $DB->get_recordset('local_hlai_quizgen_questions', [
                'userid' => $userid,
                'courseid' => $courseid,
            ]);
            $data = [];
            foreach ($rs as $question) {
                $data[] = [
                    'questiontext' => $question->questiontext,
                    'questiontype' => $question->questiontype,
                    'difficulty' => $question->difficulty,
                    'blooms_level' => $question->blooms_level,
                    'generalfeedback' => $question->generalfeedback ?? '',
                    'ai_reasoning' => $question->ai_reasoning ?? '',
                    'status' => $question->status,
                    'validation_score' => $question->validation_score,
                    'regeneration_count' => $question->regeneration_count,
                    'timecreated' => transform::datetime($question->timecreated),
                ];
            }
            $rs->close();

            if (!empty($data)) {
                writer::with_context($context)->export_data(
                    array_merge($subcontext, ['questions']),
                    (object)['questions' => $data]
                );
            }

            // Export reviews scoped to this course (as reviewer).
            $sql = "SELECT rv.*
                      FROM {local_hlai_quizgen_reviews} rv
                      JOIN {local_hlai_quizgen_questions} q ON q.id = rv.questionid
                     WHERE q.courseid = :courseid AND (rv.reviewerid = :userid OR rv.submitterid = :userid2)";
            $rs = $DB->get_recordset_sql($sql, [
                'courseid' => $courseid,
                'userid' => $userid,
                'userid2' => $userid,
            ]);
            $data = [];
            foreach ($rs as $review) {
                $data[] = [
                    'status' => $review->status,
                    'review_type' => $review->review_type,
                    'decision' => $review->decision ?? '',
                    'decision_comments' => $review->decision_comments ?? '',
                    'instructions' => $review->instructions ?? '',
                    'timecreated' => transform::datetime($review->timecreated),
                ];
            }
            $rs->close();

            if (!empty($data)) {
                writer::with_context($context)->export_data(
                    array_merge($subcontext, ['reviews']),
                    (object)['reviews' => $data]
                );
            }

            // Export logs scoped to this course via requests.
            $sql = "SELECT l.*
                      FROM {local_hlai_quizgen_logs} l
                      JOIN {local_hlai_quizgen_requests} r ON r.id = l.requestid
                     WHERE r.courseid = :courseid AND l.userid = :userid";
            $rs = $DB->get_recordset_sql($sql, [
                'courseid' => $courseid,
                'userid' => $userid,
            ]);
            $data = [];
            foreach ($rs as $log) {
                $data[] = [
                    'action' => $log->action,
                    'component' => $log->component ?? '',
                    'status' => $log->status,
                    'timecreated' => transform::datetime($log->timecreated),
                ];
            }
            $rs->close();

            if (!empty($data)) {
                writer::with_context($context)->export_data(
                    array_merge($subcontext, ['logs']),
                    (object)['logs' => $data]
                );
            }

            // Export revisions scoped to this course via reviews -> questions.
            $sql = "SELECT rev.*
                      FROM {local_hlai_quizgen_revisions} rev
                      JOIN {local_hlai_quizgen_reviews} rv ON rv.id = rev.reviewid
                      JOIN {local_hlai_quizgen_questions} q ON q.id = rv.questionid
                     WHERE q.courseid = :courseid AND rev.userid = :userid";
            $rs = $DB->get_recordset_sql($sql, [
                'courseid' => $courseid,
                'userid' => $userid,
            ]);
            $data = [];
            foreach ($rs as $revision) {
                $data[] = [
                    'changes' => $revision->changes ?? '',
                    'revision_notes' => $revision->revision_notes ?? '',
                    'timecreated' => transform::datetime($revision->timecreated),
                ];
            }
            $rs->close();

            if (!empty($data)) {
                writer::with_context($context)->export_data(
                    array_merge($subcontext, ['revisions']),
                    (object)['revisions' => $data]
                );
            }

            // Export templates scoped to this course.
            $rs = $DB->get_recordset('local_hlai_quizgen_templates', [
                'userid' => $userid,
                'courseid' => $courseid,
            ]);
            $data = [];
            foreach ($rs as $template) {
                $data[] = [
                    'name' => $template->name ?? '',
                    'description' => $template->description ?? '',
                    'config_data' => $template->config_data ?? '',
                    'timecreated' => transform::datetime($template->timecreated),
                ];
            }
            $rs->close();

            if (!empty($data)) {
                writer::with_context($context)->export_data(
                    array_merge($subcontext, ['templates']),
                    (object)['templates' => $data]
                );
            }

            // Export wizard state scoped to this course.
            $rs = $DB->get_recordset('local_hlai_quizgen_wizstate', [
                'userid' => $userid,
                'courseid' => $courseid,
            ]);
            $data = [];
            foreach ($rs as $state) {
                $data[] = [
                    'current_step' => $state->current_step,
                    'state_data' => $state->state_data ?? '',
                    'timecreated' => transform::datetime($state->timecreated),
                ];
            }
            $rs->close();

            if (!empty($data)) {
                writer::with_context($context)->export_data(
                    array_merge($subcontext, ['wizard_state']),
                    (object)['wizard_state' => $data]
                );
            }

            // Export rate limit log (global per user, no course scope).
            $rs = $DB->get_recordset('local_hlai_quizgen_ratelog', [
                'userid' => $userid,
            ]);
            $data = [];
            foreach ($rs as $entry) {
                $data[] = [
                    'limittype' => $entry->limittype ?? '',
                    'timecreated' => transform::datetime($entry->timecreated),
                ];
            }
            $rs->close();

            if (!empty($data)) {
                writer::with_context($context)->export_data(
                    array_merge($subcontext, ['ratelimit_log']),
                    (object)['ratelimit_log' => $data]
                );
            }
        }
    }

    /**
     * Delete user data for approved contexts.
     *
     * @param \context $context The context to delete data for
     * @return void
     */
    public static function delete_data_for_all_users_in_context(\context $context): void {
        global $DB;

        if ($context->contextlevel != CONTEXT_COURSE) {
            return;
        }

        $courseid = $context->instanceid;

        // Get all requests for this course and cascade-delete child records.
        $rs = $DB->get_recordset('local_hlai_quizgen_requests', ['courseid' => $courseid]);
        $requestids = [];
        foreach ($rs as $request) {
            $requestids[] = $request->id;
            self::delete_request_data($request->id);
        }
        $rs->close();

        // Delete questions in this course (and their answers/reviews/revisions) using batch operations.
        $questionids = $DB->get_fieldset_select(
            'local_hlai_quizgen_questions',
            'id',
            'courseid = :courseid',
            ['courseid' => $courseid]
        );
        self::delete_questions_cascade($questionids);
        $DB->delete_records('local_hlai_quizgen_questions', ['courseid' => $courseid]);

        // Delete wizard state scoped to this course.
        $DB->delete_records('local_hlai_quizgen_wizstate', ['courseid' => $courseid]);

        // Delete templates scoped to this course.
        $DB->delete_records('local_hlai_quizgen_templates', ['courseid' => $courseid]);

        // Delete settings scoped to this course.
        $DB->delete_records('local_hlai_quizgen_settings', ['courseid' => $courseid]);

        // Delete logs linked to requests in this course.
        if (!empty($requestids)) {
            [$insql, $inparams] = $DB->get_in_or_equal($requestids, SQL_PARAMS_NAMED, 'req');
            $DB->delete_records_select('local_hlai_quizgen_logs', "requestid " . $insql, $inparams);
        }

        // Delete rate limit logs for all users who had requests in this course.
        $userids = $DB->get_fieldset_select(
            'local_hlai_quizgen_requests',
            'DISTINCT userid',
            'courseid = :courseid',
            ['courseid' => $courseid]
        );
        // Note: ratelog has no courseid; only delete if no other course data exists.
        // This is an acceptable trade-off per Moodle privacy API guidance.
    }

    /**
     * Delete user data.
     *
     * @param approved_contextlist $contextlist Approved contexts
     * @return void
     */
    public static function delete_data_for_user(approved_contextlist $contextlist): void {
        global $DB;

        $userid = $contextlist->get_user()->id;

        foreach ($contextlist->get_contexts() as $context) {
            if ($context->contextlevel != CONTEXT_COURSE) {
                continue;
            }

            $courseid = $context->instanceid;

            // Delete user's requests and all child records.
            $rs = $DB->get_recordset('local_hlai_quizgen_requests', [
                'courseid' => $courseid,
                'userid' => $userid,
            ]);
            $requestids = [];
            foreach ($rs as $request) {
                $requestids[] = $request->id;
                self::delete_request_data($request->id);
            }
            $rs->close();

            // Delete user's questions and their child records in this course using batch operations.
            $questionids = $DB->get_fieldset_sql(
                "SELECT id FROM {local_hlai_quizgen_questions} WHERE userid = :userid AND courseid = :courseid",
                ['userid' => $userid, 'courseid' => $courseid]
            );
            self::delete_questions_cascade($questionids);
            $DB->delete_records('local_hlai_quizgen_questions', [
                'userid' => $userid,
                'courseid' => $courseid,
            ]);

            // Delete user settings scoped to this course.
            $DB->delete_records('local_hlai_quizgen_settings', [
                'userid' => $userid,
                'courseid' => $courseid,
            ]);

            // Delete user logs linked to their requests in this course.
            if (!empty($requestids)) {
                [$insql, $inparams] = $DB->get_in_or_equal($requestids, SQL_PARAMS_NAMED, 'req');
                $inparams['userid'] = $userid;
                $DB->delete_records_select(
                    'local_hlai_quizgen_logs',
                    "userid = :userid AND requestid " . $insql,
                    $inparams
                );
            }

            // Delete reviews where user is reviewer/submitter, scoped to this course.
            $sql = "DELETE FROM {local_hlai_quizgen_revisions}
                     WHERE reviewid IN (
                         SELECT rv.id
                           FROM {local_hlai_quizgen_reviews} rv
                           JOIN {local_hlai_quizgen_questions} q ON q.id = rv.questionid
                          WHERE q.courseid = :courseid AND (rv.reviewerid = :uid1 OR rv.submitterid = :uid2)
                     )";
            // Use get_recordset_sql + delete approach for DB portability.
            $sql = "SELECT rv.id
                      FROM {local_hlai_quizgen_reviews} rv
                      JOIN {local_hlai_quizgen_questions} q ON q.id = rv.questionid
                     WHERE q.courseid = :courseid AND (rv.reviewerid = :uid1 OR rv.submitterid = :uid2)";
            $rs = $DB->get_recordset_sql($sql, [
                'courseid' => $courseid,
                'uid1' => $userid,
                'uid2' => $userid,
            ]);
            foreach ($rs as $review) {
                $DB->delete_records('local_hlai_quizgen_revisions', ['reviewid' => $review->id]);
                $DB->delete_records('local_hlai_quizgen_reviews', ['id' => $review->id]);
            }
            $rs->close();

            // Delete wizard state scoped to this course.
            $DB->delete_records('local_hlai_quizgen_wizstate', [
                'userid' => $userid,
                'courseid' => $courseid,
            ]);

            // Delete templates scoped to this course.
            $DB->delete_records('local_hlai_quizgen_templates', [
                'userid' => $userid,
                'courseid' => $courseid,
            ]);

            // Delete rate limit log (global per user).
            $DB->delete_records('local_hlai_quizgen_ratelog', [
                'userid' => $userid,
            ]);
        }
    }

    /**
     * Delete data for users in approved userlist.
     *
     * @param approved_userlist $userlist Approved users
     * @return void
     */
    public static function delete_data_for_users(approved_userlist $userlist): void {
        global $DB;

        $context = $userlist->get_context();

        if ($context->contextlevel != CONTEXT_COURSE) {
            return;
        }

        $courseid = $context->instanceid;
        $userids = $userlist->get_userids();

        if (empty($userids)) {
            return;
        }

        // Bulk-fetch all request IDs for these users in this course to avoid N+1 queries.
        [$uinsql, $uinparams] = $DB->get_in_or_equal($userids, SQL_PARAMS_NAMED, 'uid');
        $uinparams['courseid'] = $courseid;
        $allrequestids = $DB->get_fieldset_select(
            'local_hlai_quizgen_requests',
            'id',
            "courseid = :courseid AND userid " . $uinsql,
            $uinparams
        );

        // Delete child data for all requests in one batch.
        foreach ($allrequestids as $requestid) {
            self::delete_request_data($requestid);
        }

        // Bulk-fetch all question IDs for these users in this course.
        $allquestionids = $DB->get_fieldset_select(
            'local_hlai_quizgen_questions',
            'id',
            "courseid = :courseid AND userid " . $uinsql,
            $uinparams
        );
        self::delete_questions_cascade($allquestionids);

        // Bulk-delete questions for all users in this course.
        $DB->delete_records_select(
            'local_hlai_quizgen_questions',
            "courseid = :courseid AND userid " . $uinsql,
            $uinparams
        );

        // Bulk-delete logs linked to these requests.
        if (!empty($allrequestids)) {
            [$rinsql, $rinparams] = $DB->get_in_or_equal($allrequestids, SQL_PARAMS_NAMED, 'req');
            $rinparams = array_merge($rinparams, $uinparams);
            $DB->delete_records_select(
                'local_hlai_quizgen_logs',
                "userid " . $uinsql . " AND requestid " . $rinsql,
                $rinparams
            );
        }

        // Bulk-delete reviews where users are reviewer/submitter, scoped to this course.
        // Break JOIN into separate select queries to avoid SQL variable concatenation.
        $courseqids = $DB->get_fieldset_select(
            'local_hlai_quizgen_questions',
            'id',
            'courseid = :courseid',
            ['courseid' => $courseid]
        );
        $reviewids = [];
        if (!empty($courseqids)) {
            [$qinsql, $qinparams] = $DB->get_in_or_equal($courseqids, SQL_PARAMS_NAMED, 'qid');
            // Reviews where reviewer is one of the users.
            $params1 = array_merge($qinparams, $uinparams);
            $revids1 = $DB->get_fieldset_select(
                'local_hlai_quizgen_reviews',
                'id',
                "questionid " . $qinsql . " AND reviewerid " . $uinsql,
                $params1
            );
            // Reviews where submitter is one of the users.
            [$uinsql2, $uinparams2] = $DB->get_in_or_equal($userids, SQL_PARAMS_NAMED, 'uid2');
            $params2 = array_merge($qinparams, $uinparams2);
            $revids2 = $DB->get_fieldset_select(
                'local_hlai_quizgen_reviews',
                'id',
                "questionid " . $qinsql . " AND submitterid " . $uinsql2,
                $params2
            );
            $reviewids = array_unique(array_merge($revids1, $revids2));
        }

        if (!empty($reviewids)) {
            [$rvinsql, $rvinparams] = $DB->get_in_or_equal($reviewids, SQL_PARAMS_NAMED, 'rv');
            $DB->delete_records_select('local_hlai_quizgen_revisions', "reviewid " . $rvinsql, $rvinparams);
            $DB->delete_records_select('local_hlai_quizgen_reviews', "id " . $rvinsql, $rvinparams);
        }

        // Bulk-delete per-user records scoped to this course.
        $DB->delete_records_select(
            'local_hlai_quizgen_settings',
            "courseid = :courseid AND userid " . $uinsql,
            $uinparams
        );
        $DB->delete_records_select(
            'local_hlai_quizgen_wizstate',
            "courseid = :courseid AND userid " . $uinsql,
            $uinparams
        );
        $DB->delete_records_select(
            'local_hlai_quizgen_templates',
            "courseid = :courseid AND userid " . $uinsql,
            $uinparams
        );
        $DB->delete_records_select(
            'local_hlai_quizgen_ratelog',
            "userid " . $uinsql,
            $uinparams
        );
    }

    /**
     * Batch-delete child records (answers, reviews, revisions) for given question IDs.
     *
     * Avoids N+1 queries by using bulk operations instead of per-question loops.
     *
     * @param array $questionids Array of question IDs
     * @return void
     */
    private static function delete_questions_cascade(array $questionids): void {
        global $DB;

        if (empty($questionids)) {
            return;
        }

        [$insql, $inparams] = $DB->get_in_or_equal($questionids, SQL_PARAMS_NAMED, 'qid');

        // Batch delete answers for all questions.
        $DB->delete_records_select('local_hlai_quizgen_answers', "questionid " . $insql, $inparams);

        // Batch get review IDs, then cascade-delete revisions, then reviews.
        $reviewids = $DB->get_fieldset_select(
            'local_hlai_quizgen_reviews',
            'id',
            "questionid " . $insql,
            $inparams
        );
        if (!empty($reviewids)) {
            [$rinsql, $rinparams] = $DB->get_in_or_equal($reviewids, SQL_PARAMS_NAMED, 'rid');
            $DB->delete_records_select('local_hlai_quizgen_revisions', "reviewid " . $rinsql, $rinparams);
        }
        $DB->delete_records_select('local_hlai_quizgen_reviews', "questionid " . $insql, $inparams);
    }

    /**
     * Delete all data for a request.
     *
     * @param int $requestid Request ID
     * @return void
     */
    private static function delete_request_data(int $requestid): void {
        global $DB;

        // Batch cascade-delete child records for all questions in this request.
        $questionids = $DB->get_fieldset_select(
            'local_hlai_quizgen_questions',
            'id',
            'requestid = :requestid',
            ['requestid' => $requestid]
        );
        self::delete_questions_cascade($questionids);

        // Delete request-level child records.
        $DB->delete_records('local_hlai_quizgen_questions', ['requestid' => $requestid]);
        $DB->delete_records('local_hlai_quizgen_topics', ['requestid' => $requestid]);
        $DB->delete_records('local_hlai_quizgen_urlcont', ['requestid' => $requestid]);
        $DB->delete_records('local_hlai_quizgen_logs', ['requestid' => $requestid]);
        $DB->delete_records('local_hlai_quizgen_requests', ['id' => $requestid]);
    }
}
